apiVersion: v1
kind: Secret
metadata:
  name: polyspace-access
stringData:
  auth-private-key.pem: |
    <generate and insert usermanager private key https://www.mathworks.com/help/polyspace_access/install/configure-the-user-manager.html>
  config-issuetracker.json: |
    <optional, if issuetracker is enabled>
    <insert issuetracker configuration json file content here>
  license.lic: |
    <insert MW license key here>
  ps-db-password: <insert polyspace access database password here>
